In [1]:
import pandas as pd 
import numpy as np
df = pd.read_csv("dirty_dataset.csv")
df.head()

,Customer ID,Customer Name,EMAIL_ADDRESS,Phone Number,Price (KES),Purchase Date,Age,City,Is Active,Quantity Sold,Internal Notes,Product Model
0,1001,Alice Mwangi,ALICE@gmail.com,+254-712-345-001,"Ksh 25,500",2024-01-15,28.0,Nairobi,yes,"1,250",NaN,Galaxy S24
1,1002,BRIAN OTIENO,brian.otieno@yahoo.com,0712 345 002,"KES 18,200.50",15/02/2024,35.0,nairobi,Yes,850,NaN,Galaxy A54
2,1003,carol wanjiku,carol@HOTMAIL.com,+254712345003,"25,500","March 5, 2024",NaN,NAIROBI,YES,"1,500",NaN,Galaxy S24 Ultra
3,1004,David Kimani,david.k@gmail.com,(0712) 345-004,"Ksh 32,000",2024-04-10,42.0,Mombasa,no,"2,300",NaN,Galaxy Z Flip
4,1005,Eve Achieng,eve@gmail.COM,0712345005,"Ksh 18,200",20/05/2024,31.0,Kisumu,No,750,NaN,Galaxy A54

In [3]:
from datacleaner import clean
clean_df = clean(df)
clean_df.head()

,customer_id,customer_name,email_address,phone_number,price_kes,purchase_date,age,city,is_active,quantity_sold,product_model
0,1001,Alice Mwangi,alice@gmail.com,+254712345001,25500.0,2024-01-15,28,Nairobi,True,1250,Galaxy S24
1,1002,Brian Otieno,brian.otieno@yahoo.com,0712345002,18200.5,2024-02-15,35,Nairobi,True,850,Galaxy A54
2,1003,Carol Wanjiku,carol@hotmail.com,+254712345003,25500.0,2024-03-05,35,Nairobi,True,1500,Galaxy S24 Ultra
3,1004,David Kimani,david.k@gmail.com,0712345004,32000.0,2024-04-10,42,Mombasa,False,2300,Galaxy Z Flip
4,1005,Eve Achieng,eve@gmail.com,0712345005,18200.0,2024-05-20,31,Kisumu,False,750,Galaxy A54